baseurl: /visible-data
exclude: ['fabfile.py']
paginate: 10
permalink: pretty
pygments: true

# site metadata
title: Visible Data
tagline: Cultural learnings of dataviz for make benefit glorious profession of journalism
default_author: Chris Amico