exclude: ['fabfile.py', 'bin']
include: ['extra']
markdown: redcarpet
paginate: 10
pygments: true
limit_posts: 5

# urls
permalink: /:categories/:year/:month/:day/:title/
baseurl: /visible-data
url: http://eyeseast.github.com/visible-data

# site metadata
title: Visible Data
tagline: Cultural learnings of dataviz for make benefit glorious profession of journalism
default_author: Chris Amico
excerpt_separator: <!-- more -->